//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ThoiTrang_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietDonhang
    {
        public int mactdh { get; set; }
        public int madh { get; set; }
        public Nullable<int> masp { get; set; }
        public string tensp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<double> thanhtien { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public Nullable<System.DateTime> ngaygiao { get; set; }
        public string tinhtrangdon { get; set; }
        public string hinhthucthanhtoan { get; set; }
        public Nullable<int> makh { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public Nullable<int> sdt { get; set; }
        public string hinhanh { get; set; }
    
        public virtual Dondathang Dondathang { get; set; }
    }
}
