//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ThoiTrang_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuyenkhoan
    {
        public int mack { get; set; }
        public int makh { get; set; }
        public string sotkgui { get; set; }
        public string tennguoigui { get; set; }
        public Nullable<System.DateTime> ngaygio { get; set; }
        public string sotknhan { get; set; }
        public string tennguoinhan { get; set; }
        public Nullable<double> sotien { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
    }
}
