//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ThoiTrang_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dondathang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dondathang()
        {
            this.ChitietDonhangs = new HashSet<ChitietDonhang>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int madh { get; set; }
        public int masp { get; set; }
        public int makh { get; set; }
        public string tensp { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public string hinhanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietDonhang> ChitietDonhangs { get; set; }
        public virtual Khachhang Khachhang { get; set; }
        public virtual Sanpham Sanpham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
