//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ThoiTrang_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int mahd { get; set; }
        public string tenhd { get; set; }
        public Nullable<int> madh { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public int manv { get; set; }
        public int makh { get; set; }
        public int masp { get; set; }
        public string tensp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<double> thanhtien { get; set; }
    
        public virtual Dondathang Dondathang { get; set; }
        public virtual Khachhang Khachhang { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
