//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ThoiTrang_Online.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLQUANAOEntities : DbContext
    {
        public QLQUANAOEntities()
            : base("name=QLQUANAOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChitietDonhang> ChitietDonhangs { get; set; }
        public virtual DbSet<Chuyenkhoan> Chuyenkhoans { get; set; }
        public virtual DbSet<Dondathang> Dondathangs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<Nhanvien> Nhanviens { get; set; }
        public virtual DbSet<Phanhoi> Phanhois { get; set; }
        public virtual DbSet<Sanpham> Sanphams { get; set; }
    }
}
