//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ThoiTrang_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phanhoi
    {
        public int makh { get; set; }
        public string tenkh { get; set; }
        public string thongtinphanhoi { get; set; }
        public string email { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
    }
}
