//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_ThoiTrang_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Dondathangs = new HashSet<Dondathang>();
        }
    
        public int masp { get; set; }
        public string tensp { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<double> giakhuyenmai { get; set; }
        public Nullable<int> soluong { get; set; }
        public string size { get; set; }
        public string hangsx { get; set; }
        public Nullable<double> gianhap { get; set; }
        public string mota { get; set; }
        public string tinhtrang { get; set; }
        public string loaisp { get; set; }
        public string khuyenmai { get; set; }
        public string hinhanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dondathang> Dondathangs { get; set; }
    }
}
